In [1]:
import pandas as pd

In [10]:
data = pd.read_csv("books.csv")

,Unnamed: 0,Title,Link,Price,Stock
1,1,Tipping the Velvet,tipping-the-velvet_999/index.html,53.74,In stock
2,2,Soumission,soumission_998/index.html,50.10,In stock
3,3,Sharp Objects,sharp-objects_997/index.html,47.82,In stock
4,4,Sapiens: A Brief History of Humankind,sapiens-a-brief-history-of-humankind_996/index...,54.23,In stock
5,5,The Requiem Red,the-requiem-red_995/index.html,22.65,In stock
...,...,...,...,...,...
995,995,Alice in Wonderland (Alice's Adventures in Won...,alice-in-wonderland-alices-adventures-in-wonde...,55.53,In stock
996,996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",ajin-demi-human-volume-1-ajin-demi-human-1_4/i...,57.06,In stock
997,997,A Spy's Devotion (The Regency Spies of London #1),a-spys-devotion-the-regency-spies-of-london-1_...,16.97,In stock
998,998,1st to Die (Women's Murder Club #1),1st-to-die-womens-murder-club-1_2/index.html,53.98,In stock
999,999,"1,000 Places to See Before You Die",1000-places-to-see-before-you-die_1/index.html,26.08,In stock

In [11]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

data = []
current_page = 1
proceed = True

while(proceed):
    print("Scraping Current page is "+str(current_page))

    url = "https://books.toscrape.com/catalogue/page-"+str(current_page)+".html"

    page = requests.get(url)

    soap = BeautifulSoup(page.text, 'html.parser')
    
    if soap.title.text == "404 Not Found":
        proceed = False
    else:
        all_books = soap.find_all('li', class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")
        
        for book in all_books:
            item = {}

            item['Title'] = book.find("img").attrs['alt']

            item['Link'] = book.find('a').attrs['href']

            item['Price'] = book.find('p',class_= "price_color").text[2:]

            item['Stock'] = book.find('p', class_="instock availability").text.strip()
            
            data.append(item)

    current_page +=1
        
df = pd.DataFrame(data)
# df.to_csv("books.csv",index=False)

Scraping Current page is 1
Scraping Current page is 2
Scraping Current page is 3
Scraping Current page is 4
Scraping Current page is 5
Scraping Current page is 6
Scraping Current page is 7
Scraping Current page is 8
Scraping Current page is 9
Scraping Current page is 10
Scraping Current page is 11
Scraping Current page is 12
Scraping Current page is 13
Scraping Current page is 14
Scraping Current page is 15
Scraping Current page is 16
Scraping Current page is 17
Scraping Current page is 18
Scraping Current page is 19
Scraping Current page is 20
Scraping Current page is 21
Scraping Current page is 22
Scraping Current page is 23
Scraping Current page is 24
Scraping Current page is 25
Scraping Current page is 26
Scraping Current page is 27
Scraping Current page is 28
Scraping Current page is 29
Scraping Current page is 30
Scraping Current page is 31
Scraping Current page is 32
Scraping Current page is 33
Scraping Current page is 34
Scraping Current page is 35
Scraping Current page is 36
Scraping Current page is 37
Scraping Current page is 38
Scraping Current page is 39
Scraping Current page is 40
Scraping Current page is 41
Scraping Current page is 42
Scraping Current page is 43
Scraping Current page is 44
Scraping Current page is 45
Scraping Current page is 46
Scraping Current page is 47
Scraping Current page is 48
Scraping Current page is 49
Scraping Current page is 50
Scraping Current page is 51

In [18]:
df.head()

,Title,Link,Price,Stock,Book_link
0,A Light in the Attic,a-light-in-the-attic_1000/index.html,51.77,In stock,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,tipping-the-velvet_999/index.html,53.74,In stock,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,soumission_998/index.html,50.10,In stock,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,sharp-objects_997/index.html,47.82,In stock,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,sapiens-a-brief-history-of-humankind_996/index...,54.23,In stock,https://books.toscrape.com/catalogue/sapiens-a...

In [21]:
df['Link'] = "https://books.toscrape.com/catalogue/" + df['Link']

In [22]:
df['Link']

0      https://books.toscrape.com/catalogue/a-light-i...
1      https://books.toscrape.com/catalogue/tipping-t...
2      https://books.toscrape.com/catalogue/soumissio...
3      https://books.toscrape.com/catalogue/sharp-obj...
4      https://books.toscrape.com/catalogue/sapiens-a...
                             ...
995    https://books.toscrape.com/catalogue/alice-in-...
996    https://books.toscrape.com/catalogue/ajin-demi...
997    https://books.toscrape.com/catalogue/a-spys-de...
998    https://books.toscrape.com/catalogue/1st-to-di...
999    https://books.toscrape.com/catalogue/1000-plac...
Name: Link, Length: 1000, dtype: object

In [23]:
df.head()

,Title,Link,Price,Stock
0,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...,51.77,In stock
1,Tipping the Velvet,https://books.toscrape.com/catalogue/tipping-t...,53.74,In stock
2,Soumission,https://books.toscrape.com/catalogue/soumissio...,50.10,In stock
3,Sharp Objects,https://books.toscrape.com/catalogue/sharp-obj...,47.82,In stock
4,Sapiens: A Brief History of Humankind,https://books.toscrape.com/catalogue/sapiens-a...,54.23,In stock

In [24]:
df.to_csv(r'C:\Users\BP\Downloads\webScrapping\main_book.csv',index = False)